networks:
  common:

services:
  # This container is used for things that should only run once regardless of
  # the number of game servers used, for instance database migrations
  maintenance:
    build:
      context: .
      dockerfile: Dockerfile-arm32
  backend:
    build:
      context: .
      dockerfile: Dockerfile-arm32
  supervisor:
    build:
      context: .
      dockerfile: Dockerfile-arm32
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend-arm32
