networks:
  common:

services:
  # This container is used for things that should only run once regardless of
  # the number of game servers used, for instance database migrations
  maintenance:
    build:
      context: .
      dockerfile: Dockerfile-arm64
    image: ${BACKEND_DOCKER_REPOSITORY}:${TAGGED_VERSION}
  backend:
    build:
      context: .
      dockerfile: Dockerfile-arm64
    image: ${BACKEND_DOCKER_REPOSITORY}:${TAGGED_VERSION}
  supervisor:
    build:
      context: .
      dockerfile: Dockerfile-arm64
    image: ${BACKEND_DOCKER_REPOSITORY}:${TAGGED_VERSION}
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend-arm64
    image: ${FRONTEND_DOCKER_REPOSITORY}:${TAGGED_VERSION}
